/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.Market;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import Business.*;
import Business.Market.Market;
import Interface.Customer.ManageCustomerJPanel;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Vaibhavi
 */
public class ManageMarketJPanel extends javax.swing.JPanel {

    /**
     * Creates new form Market
     */
    private JPanel userProcessContainer;
    private Business business;
    
    public ManageMarketJPanel(JPanel userProcessContainer,Business business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.business = business;
        populateTable();
    }
    
    public void populateTable()
    {
        DefaultTableModel defaultTableModel = (DefaultTableModel)manageMarketJTable.getModel();
        defaultTableModel.setRowCount(0);
        
        for(Market market : business.getMarketDirectory().getMarketDirectory())
        {
            Object row[] = new Object[3];
            row[0] = market;
            row[1] = market.getMarketType();
            row[2] = market.getTotalCustomers();
            defaultTableModel.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        manageMarketJTable = new javax.swing.JTable();
        searchMarketBtn = new javax.swing.JButton();
        marketIdTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        addMarketBtn = new javax.swing.JButton();
        deleteMarketBtn = new javax.swing.JButton();
        displayMarketBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        manageCustomersBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setBackground(new java.awt.Color(0, 102, 102));
        jLabel1.setFont(new java.awt.Font("Georgia", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Manage Market ");
        jLabel1.setOpaque(true);

        manageMarketJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Market ID", "Market", "Total Number of Customers"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(manageMarketJTable);

        searchMarketBtn.setBackground(new java.awt.Color(0, 102, 102));
        searchMarketBtn.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        searchMarketBtn.setForeground(new java.awt.Color(255, 255, 255));
        searchMarketBtn.setText("Search Market");
        searchMarketBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.darkGray, null, null));
        searchMarketBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchMarketBtnActionPerformed(evt);
            }
        });

        marketIdTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                marketIdTextFieldKeyTyped(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel2.setText("Market ID :");

        addMarketBtn.setBackground(new java.awt.Color(0, 102, 102));
        addMarketBtn.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        addMarketBtn.setForeground(new java.awt.Color(255, 255, 255));
        addMarketBtn.setText("Add Market >>");
        addMarketBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.darkGray, null, null));
        addMarketBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMarketBtnActionPerformed(evt);
            }
        });

        deleteMarketBtn.setBackground(new java.awt.Color(0, 102, 102));
        deleteMarketBtn.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        deleteMarketBtn.setForeground(new java.awt.Color(255, 255, 255));
        deleteMarketBtn.setText("Delete Market >>");
        deleteMarketBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.darkGray, null, null));
        deleteMarketBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteMarketBtnActionPerformed(evt);
            }
        });

        displayMarketBtn.setBackground(new java.awt.Color(0, 102, 102));
        displayMarketBtn.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        displayMarketBtn.setForeground(new java.awt.Color(255, 255, 255));
        displayMarketBtn.setText("Update/Display Market >>");
        displayMarketBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.darkGray, null, null));
        displayMarketBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayMarketBtnActionPerformed(evt);
            }
        });

        backBtn.setBackground(new java.awt.Color(102, 0, 0));
        backBtn.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        backBtn.setForeground(new java.awt.Color(255, 255, 255));
        backBtn.setText("<< Back");
        backBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.darkGray, null, null));
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        manageCustomersBtn.setBackground(new java.awt.Color(0, 102, 102));
        manageCustomersBtn.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        manageCustomersBtn.setForeground(new java.awt.Color(255, 255, 255));
        manageCustomersBtn.setText("Manage Customers >>");
        manageCustomersBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.darkGray, null, null));
        manageCustomersBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageCustomersBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 525, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(37, 37, 37)
                        .addComponent(marketIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(searchMarketBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(displayMarketBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(manageCustomersBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(72, 72, 72)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(addMarketBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(deleteMarketBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(marketIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(searchMarketBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addMarketBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(displayMarketBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(deleteMarketBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(manageCustomersBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void deleteMarketBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteMarketBtnActionPerformed
        
        int selectedRow = manageMarketJTable.getSelectedRow();
        
        if(selectedRow >= 0)
        {
            Market market = (Market)manageMarketJTable.getValueAt(selectedRow, 0);
            business.getMarketDirectory().deleteMarket(market);
            populateTable();
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Please select a row.", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_deleteMarketBtnActionPerformed

    private void displayMarketBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayMarketBtnActionPerformed
        
        int selectedRow = manageMarketJTable.getSelectedRow(); 
        
        if(selectedRow >= 0)
        {
            Market market = (Market)manageMarketJTable.getValueAt(selectedRow, 0);
            DisplayMarketJPanel displayMarketJPanel = new DisplayMarketJPanel(userProcessContainer,business, market);
            userProcessContainer.add("DisplayMarketJPanel",displayMarketJPanel);
            CardLayout layout = (CardLayout)userProcessContainer.getLayout();
            layout.next(userProcessContainer);
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Please select a row.", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_displayMarketBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backBtnActionPerformed

    private void manageCustomersBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageCustomersBtnActionPerformed
        
        int selectedRow = manageMarketJTable.getSelectedRow(); 
        
        if(selectedRow >= 0)
        {
            Market market = (Market)manageMarketJTable.getValueAt(selectedRow, 0);
            ManageCustomerJPanel manageCustomerJPanel = new ManageCustomerJPanel(userProcessContainer,market);
            userProcessContainer.add("ManageCustomerJPanel",manageCustomerJPanel);
            CardLayout layout = (CardLayout)userProcessContainer.getLayout();
            layout.next(userProcessContainer);
        }
        else
        {
           JOptionPane.showMessageDialog(null, "Please select a row.","Warning",JOptionPane.WARNING_MESSAGE); 
        }
    }//GEN-LAST:event_manageCustomersBtnActionPerformed

    private void marketIdTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_marketIdTextFieldKeyTyped
        
        char ch = evt.getKeyChar();
        if(!(Character.isDigit(ch)) || (ch == KeyEvent.VK_BACK_SPACE) || (ch == KeyEvent.VK_DELETE))
        {
            evt.consume();
            if(Character.isAlphabetic(ch) || Character.isSpaceChar(ch))
            JOptionPane.showMessageDialog(null,"Enter numerical values only.");
        }
    }//GEN-LAST:event_marketIdTextFieldKeyTyped

    private void searchMarketBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchMarketBtnActionPerformed
        
        if(!marketIdTextField.getText().isEmpty())
        {
            Market market = business.getMarketDirectory().searchMarket(Integer.parseInt(marketIdTextField.getText()));
            
            if(market != null)
            {
                DisplayMarketJPanel displayMarketJPanel = new DisplayMarketJPanel(userProcessContainer, business, market);
                userProcessContainer.add("DisplayMarketJPanel",displayMarketJPanel);
                CardLayout layout = (CardLayout)userProcessContainer.getLayout();
                layout.next(userProcessContainer);
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Market does not exist.","Information",JOptionPane.INFORMATION_MESSAGE);
            }
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Please enter the MarketId.","Warning",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_searchMarketBtnActionPerformed

    private void addMarketBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMarketBtnActionPerformed
        
        CreateMarketJPanel createMarketJPanel = new CreateMarketJPanel(userProcessContainer,business);
        userProcessContainer.add("CreateMarketJPanel",createMarketJPanel);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_addMarketBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addMarketBtn;
    private javax.swing.JButton backBtn;
    private javax.swing.JButton deleteMarketBtn;
    private javax.swing.JButton displayMarketBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton manageCustomersBtn;
    private javax.swing.JTable manageMarketJTable;
    private javax.swing.JTextField marketIdTextField;
    private javax.swing.JButton searchMarketBtn;
    // End of variables declaration//GEN-END:variables
}
