/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.admin;

import Business.Business;
import Interface.Person.ManagePersonJPanel;
import Interface.Market.ManageMarketJPanel;
import Interface.SalesPerson.ManageSalesPersonJPanel;
import Interface.Suppliers.ManageSuppliersJPanel;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author sreer
 */
public class ManageRolesJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageRolesJPanel
     */
    JPanel cardSeqjPanel;
    Business business;
    public ManageRolesJPanel(JPanel cardSeqjPanel,Business business) {
        initComponents();
        this.cardSeqjPanel=cardSeqjPanel;
        this.business=business;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        manageSuppliersBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        manageUsersBtn = new javax.swing.JButton();
        manageSalesPersonBtn = new javax.swing.JButton();
        manageMarketBtn = new javax.swing.JButton();
        mangPerson = new javax.swing.JToggleButton();
        mapUserSupplierjButton = new javax.swing.JButton();
        mapUsersalesjButton = new javax.swing.JButton();
        mapCustomerPersonjButton = new javax.swing.JButton();

        manageSuppliersBtn.setText("Manage Suppliers");
        manageSuppliersBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageSuppliersBtnActionPerformed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Manage Roles Menu");

        manageUsersBtn.setText("Manage Users");
        manageUsersBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageUsersBtnActionPerformed(evt);
            }
        });

        manageSalesPersonBtn.setText("Manage Sales Person");
        manageSalesPersonBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageSalesPersonBtnActionPerformed(evt);
            }
        });

        manageMarketBtn.setText("Manage Market");
        manageMarketBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageMarketBtnActionPerformed(evt);
            }
        });

        mangPerson.setText("Manage Person");
        mangPerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mangPersonActionPerformed(evt);
            }
        });

        mapUserSupplierjButton.setText("Map Supplier-User");
        mapUserSupplierjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mapUserSupplierjButtonActionPerformed(evt);
            }
        });

        mapUsersalesjButton.setText("Map Sales-User");
        mapUsersalesjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mapUsersalesjButtonActionPerformed(evt);
            }
        });

        mapCustomerPersonjButton.setText("Map Customer-Person");
        mapCustomerPersonjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mapCustomerPersonjButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(manageMarketBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                    .addComponent(manageUsersBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(manageSuppliersBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                    .addComponent(manageSalesPersonBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(mangPerson, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mapUserSupplierjButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mapUsersalesjButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mapCustomerPersonjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(765, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(manageUsersBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(manageSuppliersBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(manageSalesPersonBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(manageMarketBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mangPerson)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mapUserSupplierjButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mapUsersalesjButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mapCustomerPersonjButton)
                .addContainerGap(240, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void manageUsersBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageUsersBtnActionPerformed
        UserJPanel amf = new UserJPanel(cardSeqjPanel,business);
        cardSeqjPanel.add("UserJPanel",amf);
        CardLayout layout = (CardLayout) cardSeqjPanel.getLayout();
        layout.next(cardSeqjPanel);
    }//GEN-LAST:event_manageUsersBtnActionPerformed


    private void mangPersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mangPersonActionPerformed
        // TODO add your handling code here:

        ManagePersonJPanel mp=new ManagePersonJPanel(cardSeqjPanel,business);
        cardSeqjPanel.add("UserJPanel",mp);
        CardLayout layout = (CardLayout) cardSeqjPanel.getLayout();
        layout.next(cardSeqjPanel);

    }//GEN-LAST:event_mangPersonActionPerformed

    private void manageSuppliersBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageSuppliersBtnActionPerformed

        ManageSuppliersJPanel manageSuppliersJPanel = new ManageSuppliersJPanel(cardSeqjPanel,business);
        cardSeqjPanel.add("ManageSuppliersJPanel",manageSuppliersJPanel);
        CardLayout layout = (CardLayout)cardSeqjPanel.getLayout();
        layout.next(cardSeqjPanel);

    }//GEN-LAST:event_manageSuppliersBtnActionPerformed


    private void mapUserSupplierjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mapUserSupplierjButtonActionPerformed
        // TODO add your handling code here:

        MappingUserSupplier mu=new MappingUserSupplier(business, cardSeqjPanel);
        cardSeqjPanel.add("UserJPanel",mu);
        CardLayout layout = (CardLayout) cardSeqjPanel.getLayout();
        layout.next(cardSeqjPanel);

    }//GEN-LAST:event_mapUserSupplierjButtonActionPerformed

    private void manageSalesPersonBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageSalesPersonBtnActionPerformed
        // TODO add your handling code here:
        ManageSalesPersonJPanel manageSalesPersonJPanel = new ManageSalesPersonJPanel(cardSeqjPanel,business);
        cardSeqjPanel.add("ManageSalesPersonJPanel",manageSalesPersonJPanel);
        CardLayout layout = (CardLayout) cardSeqjPanel.getLayout();
        layout.next(cardSeqjPanel);
    }//GEN-LAST:event_manageSalesPersonBtnActionPerformed

    private void manageMarketBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageMarketBtnActionPerformed
        
        ManageMarketJPanel manageMarketJPanel = new ManageMarketJPanel(cardSeqjPanel,business);
        cardSeqjPanel.add("ManageMarketJPanel",manageMarketJPanel);
        CardLayout layout = (CardLayout)cardSeqjPanel.getLayout();
        layout.next(cardSeqjPanel);
    }//GEN-LAST:event_manageMarketBtnActionPerformed

    private void mapUsersalesjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mapUsersalesjButtonActionPerformed
        MappingUserSalesPersonJPanel manageMarketJPanel = new MappingUserSalesPersonJPanel(cardSeqjPanel,business);
        cardSeqjPanel.add("ManageMarketJPanel",manageMarketJPanel);
        CardLayout layout = (CardLayout)cardSeqjPanel.getLayout();
        layout.next(cardSeqjPanel);
    }//GEN-LAST:event_mapUsersalesjButtonActionPerformed

    private void mapCustomerPersonjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mapCustomerPersonjButtonActionPerformed
        MappingCustomerPerson manageMarketJPanel = new MappingCustomerPerson(cardSeqjPanel,business);
        cardSeqjPanel.add("ManageMarketJPanel",manageMarketJPanel);
        CardLayout layout = (CardLayout)cardSeqjPanel.getLayout();
        layout.next(cardSeqjPanel);
    }//GEN-LAST:event_mapCustomerPersonjButtonActionPerformed




    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton manageMarketBtn;
    private javax.swing.JButton manageSalesPersonBtn;
    private javax.swing.JButton manageSuppliersBtn;
    private javax.swing.JButton manageUsersBtn;
    private javax.swing.JToggleButton mangPerson;
    private javax.swing.JButton mapCustomerPersonjButton;
    private javax.swing.JButton mapUserSupplierjButton;
    private javax.swing.JButton mapUsersalesjButton;
    // End of variables declaration//GEN-END:variables
}
