/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.supplierJPanel;

import Business.Business;
import Business.Users.User;
import Business.supplier.Product;
import Business.supplier.Supplier;
import Interface.login.LoginForm;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ninni
 */
public class ManageProductsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageProductsJPanel
     */
    JPanel cardSeqJPanel;
    Business business;
    User i;
    Supplier sup;

    public ManageProductsJPanel(JPanel cardSeqJPanel, Business business) {
        initComponents();

        this.cardSeqJPanel = cardSeqJPanel;
        this.business = business;

        i = business.getLoggedUser();
        sup = business.getMapSupplierUserDirectory().searchSupplier(i);
        System.out.println("checking supplier name" + sup);
        refreshTable();

    }

    public void refreshTable() {
        int rowCount = productTable.getRowCount();

        DefaultTableModel dtm = (DefaultTableModel) productTable.getModel();

        for (int i = rowCount - 1; i >= 0; i--) {
            dtm.removeRow(i);
        }
        System.out.println("checking supplier name" + sup);

        LbSupplierNm.setText(sup.getSupplierName());
        System.out.println("checking supplier name" + sup);
        for (Product p : sup.getProductDirectory().getProduct()) {

            Object row[] = new Object[5];
            row[0] = p;                   // we hv created toString() so that, inspite of giving address of object we will get product name
            row[1] = p.getProductName();
            row[2] = p.getPrice();
            row[3] = p.getQuantity();
            row[4] = p.isAvail();
            dtm.addRow(row);

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        deleteBt = new javax.swing.JButton();
        backTb = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        productIdTx = new javax.swing.JTextField();
        searchBt = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        productTable = new javax.swing.JTable();
        viewBt = new javax.swing.JButton();
        addTb = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        LbSupplierNm = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        deleteBt.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        deleteBt.setText("DELETE Product");
        deleteBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtActionPerformed(evt);
            }
        });

        backTb.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        backTb.setText("<<BACK");
        backTb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backTbActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("Product Id");

        productIdTx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productIdTxActionPerformed(evt);
            }
        });

        searchBt.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        searchBt.setText("SEARCH");
        searchBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtActionPerformed(evt);
            }
        });

        productTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Product ID", "Product Name", "Price", "Quantity", "Availability"
            }
        ));
        jScrollPane1.setViewportView(productTable);

        viewBt.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        viewBt.setText("VIEW Product");
        viewBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewBtActionPerformed(evt);
            }
        });

        addTb.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        addTb.setText("ADD Product");
        addTb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTbActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Supplier Name");

        LbSupplierNm.setEditable(false);

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Manage Products");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LbSupplierNm, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(viewBt, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(addTb, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(deleteBt, javax.swing.GroupLayout.Alignment.TRAILING)))
            .addGroup(layout.createSequentialGroup()
                .addComponent(backTb)
                .addGap(165, 165, 165)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(278, 278, 278))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(productIdTx, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(searchBt, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, Short.MAX_VALUE)
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LbSupplierNm, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(searchBt)
                    .addComponent(productIdTx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backTb))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addTb)
                    .addComponent(viewBt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(deleteBt)
                .addGap(236, 236, 236))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void deleteBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtActionPerformed

        int selectRow = productTable.getSelectedRow();                 // it will select the row from the table

        if (selectRow < 0) {                                                           // if selectedRow <0 means the row is not selected
            JOptionPane.showMessageDialog(null, "please select any row from the first table", "WARNING", JOptionPane.WARNING_MESSAGE);
            return;
        }

        Product p = (Product) productTable.getValueAt(selectRow, 0);         // getValueAt() returns the cell value at row and col.

        //  int i = business.getSupplierDirectory().addSupplier().getSupplierId();
        sup.getProductDirectory().getProduct().remove(p);

        // business.getSupplierDirectory().getSupplierDirectory().get(i).getProductDirectory().getProduct().remove(p);
        refreshTable();

        // TODO add your handling code here:
    }//GEN-LAST:event_deleteBtActionPerformed

    private void backTbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backTbActionPerformed

        cardSeqJPanel.remove(this);
        CardLayout layout = (CardLayout) cardSeqJPanel.getLayout();
        layout.previous(cardSeqJPanel);

        // TODO add your handling code here:
    }//GEN-LAST:event_backTbActionPerformed

    private void searchBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtActionPerformed

        // int i = business.getSupplierDirectory().addSupplier().getSupplierId();
        //Product p = business.getSupplierDirectory().getSupplierDirectory().get(i).getProductDirectory().getProductById(Integer.parseInt(productIdTx.getText()));
        Product p = sup.getProductDirectory().getProductById(Integer.parseInt(productIdTx.getText()));

        ViewUpdateProductsJPanel sp = new ViewUpdateProductsJPanel(cardSeqJPanel, business, p);
        cardSeqJPanel.add("search supplier panel", sp);
        CardLayout layout = (CardLayout) cardSeqJPanel.getLayout();
        layout.next(cardSeqJPanel);

        // TODO add your handling code here:
    }//GEN-LAST:event_searchBtActionPerformed

    private void viewBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewBtActionPerformed

        int selectRow = productTable.getSelectedRow();

        if (selectRow < 0) {
            JOptionPane.showMessageDialog(null, "please select any row from the first table", "WARNING", JOptionPane.WARNING_MESSAGE);
            return;
        }

        Product s = (Product) productTable.getValueAt(selectRow, 0);

        ViewUpdateProductsJPanel vs = new ViewUpdateProductsJPanel(cardSeqJPanel, business, s);
        cardSeqJPanel.add("view supplier panel", vs);
        CardLayout layout = (CardLayout) cardSeqJPanel.getLayout();
        layout.next(cardSeqJPanel);

        // TODO add your handling code here:
    }//GEN-LAST:event_viewBtActionPerformed

    private void addTbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTbActionPerformed

        AddProductsJPanel cp = new AddProductsJPanel(cardSeqJPanel, business);

        cardSeqJPanel.add("create supplier panel", cp);
        CardLayout layout = (CardLayout) cardSeqJPanel.getLayout();
        layout.next(cardSeqJPanel);

        // TODO add your handling code here:
    }//GEN-LAST:event_addTbActionPerformed

    private void productIdTxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productIdTxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productIdTxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField LbSupplierNm;
    private javax.swing.JButton addTb;
    private javax.swing.JButton backTb;
    private javax.swing.JButton deleteBt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField productIdTx;
    private javax.swing.JTable productTable;
    private javax.swing.JButton searchBt;
    private javax.swing.JButton viewBt;
    // End of variables declaration//GEN-END:variables
}
