/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.supplierJPanel;

import Business.Business;
import Business.Users.User;
import Business.supplier.Product;
import Business.supplier.Supplier;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Ninni
 */
public class ViewUpdateProductsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AddProducts
     */
    JPanel cardSeqJPanel;
    Business business;
    Product product;
    User i;
    Supplier sup;

    public ViewUpdateProductsJPanel(JPanel cardSeqJPanel, Business business, Product product) {
        initComponents();
        this.cardSeqJPanel = cardSeqJPanel;
        this.business = business;
        this.product = product;
        nameTx.setEditable(false);
        priceTx.setEditable(false);
        availTx.setEditable(false);
        idTx.setEditable(false);
        quantityTx.setEditable(false);
        product=product;
        i = business.getLoggedUser();
        sup = business.getMapSupplierUserDirectory().searchSupplier(i);

        supplierNameLabel.setText(sup.getSupplierName());

        nameTx.setText(this.product.getProductName());
        priceTx.setText(String.valueOf(this.product.getPrice()));
        quantityTx.setText(String.valueOf(this.product.getQuantity()));
        availTx.setText(String.valueOf(this.product.isAvail()));
        idTx.setText(String.valueOf(this.product.getProductId()));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        updateBt = new javax.swing.JButton();
        quantityTx = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        nameTx = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        idTx = new javax.swing.JTextField();
        priceTx = new javax.swing.JTextField();
        backBt = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        availTx = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        saveBt = new javax.swing.JButton();
        supplierNameLabel = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setText("Quantity");

        updateBt.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        updateBt.setText("Update Product");
        updateBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Name");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText(" Id");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("Price");

        priceTx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceTxActionPerformed(evt);
            }
        });

        backBt.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        backBt.setText("<<BACK");
        backBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setText("Availability");

        jLabel4.setFont(new java.awt.Font("Dialog", 3, 36)); // NOI18N
        jLabel4.setText("VIEW PRODUCTS");

        saveBt.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        saveBt.setText("SAVE");
        saveBt.setEnabled(false);
        saveBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtActionPerformed(evt);
            }
        });

        supplierNameLabel.setText(" ");

        jLabel7.setText("Supplier Name");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(supplierNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(backBt))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(saveBt)
                        .addGap(62, 62, 62)
                        .addComponent(updateBt))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(78, 78, 78)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(quantityTx, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(availTx, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(priceTx, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(idTx, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nameTx, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(supplierNameLabel)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameTx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idTx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(priceTx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(quantityTx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(availTx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveBt)
                    .addComponent(updateBt))
                .addGap(25, 25, 25)
                .addComponent(backBt)
                .addGap(33, 33, 33))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void updateBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtActionPerformed

        nameTx.setEditable(true);
        priceTx.setEditable(true);
        availTx.setEditable(true);
        idTx.setEditable(true);
        quantityTx.setEditable(true);
 JOptionPane.showMessageDialog(null, "update now", "WARNING", JOptionPane.INFORMATION_MESSAGE);

        saveBt.setEnabled(true);


    }//GEN-LAST:event_updateBtActionPerformed

    private void priceTxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceTxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceTxActionPerformed

    private void backBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtActionPerformed

        cardSeqJPanel.remove(this);
        Component[] componentArray = cardSeqJPanel.getComponents();        // to get all the components as these values will be added
        Component component = componentArray[componentArray.length - 1];

        ManageProductsJPanel ms = (ManageProductsJPanel) component;
        ms.refreshTable();

        CardLayout layout = (CardLayout) cardSeqJPanel.getLayout();
        layout.previous(cardSeqJPanel);
        // TODO add your handling code here:
    }//GEN-LAST:event_backBtActionPerformed

    private void saveBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtActionPerformed

        product.setAvail(Boolean.parseBoolean(availTx.getText()));
        product.setPrice(Double.parseDouble(priceTx.getText()));
        product.setProductId(Integer.parseInt(idTx.getText()));
        product.setProductName(nameTx.getText());
        product.setQuantity(Integer.parseInt(quantityTx.getText()));

        JOptionPane.showMessageDialog(null, "saved successfully", "WARNING", JOptionPane.INFORMATION_MESSAGE);


    }//GEN-LAST:event_saveBtActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField availTx;
    private javax.swing.JButton backBt;
    private javax.swing.JTextField idTx;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField nameTx;
    private javax.swing.JTextField priceTx;
    private javax.swing.JTextField quantityTx;
    private javax.swing.JButton saveBt;
    private javax.swing.JLabel supplierNameLabel;
    private javax.swing.JButton updateBt;
    // End of variables declaration//GEN-END:variables
}
