/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.admin.analytics;

import Business.Business;
import Business.ConfigureABusiness;
import Interface.admin.SalesPersonPerformanceJPanel;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author sreer
 */
public class SalesMenuJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SalesMenu
     */
    JPanel UserProcessJPanel;
    Business business;
    public SalesMenuJPanel(JPanel UserProcessJPanel, Business business) {
        initComponents();
        this.UserProcessJPanel=UserProcessJPanel;
        this.business=business; //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        totalSalesjButton = new javax.swing.JButton();
        salesByMarketjButton = new javax.swing.JButton();
        mostSoldProductjButton = new javax.swing.JButton();
        toptebjButton = new javax.swing.JButton();
        salesPersonPerformanceBtn = new javax.swing.JButton();

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Sales Performance Menu");

        totalSalesjButton.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.darcula.selection.color1"));
        totalSalesjButton.setForeground(javax.swing.UIManager.getDefaults().getColor("Button.darkShadow"));
        totalSalesjButton.setText("Totals Sales");
        totalSalesjButton.setToolTipText("");
        totalSalesjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalSalesjButtonActionPerformed(evt);
            }
        });

        salesByMarketjButton.setText("Sales By Market");
        salesByMarketjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salesByMarketjButtonActionPerformed(evt);
            }
        });

        mostSoldProductjButton.setText("Most Sold Product");
        mostSoldProductjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostSoldProductjButtonActionPerformed(evt);
            }
        });

        toptebjButton.setText("Best Sales Person From Market");
        toptebjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toptebjButtonActionPerformed(evt);
            }
        });

        salesPersonPerformanceBtn.setText("Sales Person Performance");
        salesPersonPerformanceBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salesPersonPerformanceBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(salesPersonPerformanceBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(mostSoldProductjButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(salesByMarketjButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(totalSalesjButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(toptebjButton, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)))
                .addContainerGap(144, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(totalSalesjButton)
                .addGap(18, 18, 18)
                .addComponent(salesByMarketjButton)
                .addGap(18, 18, 18)
                .addComponent(mostSoldProductjButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(toptebjButton)
                .addGap(18, 18, 18)
                .addComponent(salesPersonPerformanceBtn)
                .addContainerGap(43, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void totalSalesjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalSalesjButtonActionPerformed
//        System.out.println(business.getPurchaseOrderCat().getPurchaseOrderCat().get(0).getTotalPrice());
        viewAllSalesJPanel amf = new viewAllSalesJPanel(UserProcessJPanel,business);
        
        UserProcessJPanel.add("viewAllSalesJPanel",amf);
        CardLayout layout = (CardLayout) UserProcessJPanel.getLayout();
        layout.next(UserProcessJPanel);
    }//GEN-LAST:event_totalSalesjButtonActionPerformed

    private void salesByMarketjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salesByMarketjButtonActionPerformed
        SalesRevenueByMarketJPanel amf = new SalesRevenueByMarketJPanel(UserProcessJPanel,business);
        
        UserProcessJPanel.add("SalesRevenueByMarketJPanel",amf);
        CardLayout layout = (CardLayout) UserProcessJPanel.getLayout();
        layout.next(UserProcessJPanel);
    }//GEN-LAST:event_salesByMarketjButtonActionPerformed

    private void toptebjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toptebjButtonActionPerformed
       topTenJPanel amf = new topTenJPanel(UserProcessJPanel,business);
        
        UserProcessJPanel.add("topTenJPanel",amf);
        CardLayout layout = (CardLayout) UserProcessJPanel.getLayout();
        layout.next(UserProcessJPanel);
    }//GEN-LAST:event_toptebjButtonActionPerformed

    private void mostSoldProductjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostSoldProductjButtonActionPerformed
        
        TopSoldProductJPanel amf = new TopSoldProductJPanel(UserProcessJPanel,business);
        UserProcessJPanel.add("TopSoldProductJPanel",amf);
        CardLayout layout = (CardLayout) UserProcessJPanel.getLayout();
        layout.next(UserProcessJPanel);
    }//GEN-LAST:event_mostSoldProductjButtonActionPerformed

    private void salesPersonPerformanceBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salesPersonPerformanceBtnActionPerformed
        // TODO add your handling code here:
        SalesPersonPerformanceJPanel salesPersonPerformanceJPanel = new SalesPersonPerformanceJPanel(UserProcessJPanel,business);
        UserProcessJPanel.add("SalesPersonPerformanceJPanel",salesPersonPerformanceJPanel);
        CardLayout layout = (CardLayout) UserProcessJPanel.getLayout();
        layout.next(UserProcessJPanel);
    }//GEN-LAST:event_salesPersonPerformanceBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton mostSoldProductjButton;
    private javax.swing.JButton salesByMarketjButton;
    private javax.swing.JButton salesPersonPerformanceBtn;
    private javax.swing.JButton toptebjButton;
    private javax.swing.JButton totalSalesjButton;
    // End of variables declaration//GEN-END:variables
}