/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.sales;

import Business.Business;
import Business.sales.OrderItems;
import Business.sales.PurchaseOrder;
import java.awt.BorderLayout;
import java.awt.CardLayout;
import java.awt.LayoutManager;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.data.general.DefaultPieDataset;
import org.jfree.data.general.PieDataset;

/**
 *
 * @author sreer
 */
public class MySalesPerformance extends javax.swing.JPanel {

    /**
     * Creates new form MySalesPerformance
     */
    public JFreeChart createChart( PieDataset dataset ) {
      JFreeChart chart = ChartFactory.createPieChart(      
         "Sales Performance",   // chart title 
         dataset,          // data    
         true,             // include legend   
         true, 
         false);

      return chart;
   }
    Business business;
    public MySalesPerformance(Business business) {
        initComponents();
        this.business = business;
        
    }
    private PieDataset createDataset( ) {
      double above = 0;
      double below = 0;
      DefaultPieDataset dataset = new DefaultPieDataset( );
      for(PurchaseOrder po : business.getPurchaseOrderCat().getPurchaseOrderCat()){
          for(OrderItems oi : po.getOrderItemsCat().getOrderItemsCat() ){
              if(oi.isAboveTarget()){
                  above+=oi.getReqQantity();
              }
              else{
                  below+=oi.getReqQantity();
              }
          }
      }
      dataset.setValue( "Number of sales above target: "+String.valueOf(above) , above );  
      dataset.setValue( "Number of sales below target: "+String.valueOf(below) , below );  
      return dataset;         
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        viewStatsjButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        viewStatsjButton.setText("View Stats");
        viewStatsjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewStatsjButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("View my Performance");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(viewStatsjButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(viewStatsjButton)
                .addContainerGap(202, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void viewStatsjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewStatsjButtonActionPerformed
        JFreeChart chart = createChart(createDataset());
        ChartFrame frame = new ChartFrame("Results", chart);
        frame.pack();
        frame.setVisible(true);
    }//GEN-LAST:event_viewStatsjButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton viewStatsjButton;
    // End of variables declaration//GEN-END:variables
}
