/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.sales;

import Business.Business;
import Business.Market.Market;
import Business.Market.MarketDirectory;
import Business.customer.Customer;
import Business.supplier.Supplier;
import Interface.Customer.CreateCustomerJPanel;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JPanel;

/**
 *
 * @author sreer
 */
public class SalesCusSelectJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SalesCusSelectJPanel
     */
    JPanel userProcessContainerjPanel;
    Business business;
    public SalesCusSelectJPanel(JPanel userProcessContainerjPanel, Business business) {
        initComponents();
        this.business=business;
        this.userProcessContainerjPanel=userProcessContainerjPanel;
        populateMarketType();
        customerjComboBox.setEnabled(false);
        marketTypejComboBox.setEnabled(false);
        customerjComboBox.setEnabled(false);
        selretjButton.setEnabled(false);
        
    }
    private void populateMarketType() {
        MarketDirectory md = business.getMarketDirectory();
        marketTypejComboBox.removeAllItems();
        for(Market market : md.getMarketDirectory()){
            marketTypejComboBox.addItem(market.getMarketType());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        retCusjButton = new javax.swing.JButton();
        newCusjButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        marketTypejComboBox = new javax.swing.JComboBox<>();
        customerjComboBox = new javax.swing.JComboBox<>();
        selretjButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Select Customer Menu");

        retCusjButton.setText("Returning Customer");
        retCusjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retCusjButtonActionPerformed(evt);
            }
        });

        newCusjButton.setText("New Customer");
        newCusjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newCusjButtonActionPerformed(evt);
            }
        });

        marketTypejComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        marketTypejComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                marketTypejComboBoxItemStateChanged(evt);
            }
        });

        customerjComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        selretjButton.setText("Select");
        selretjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selretjButtonActionPerformed(evt);
            }
        });

        jLabel4.setText("Market Type:");

        jLabel5.setText("Customer:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(marketTypejComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(retCusjButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(customerjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(selretjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(newCusjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(522, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(retCusjButton)
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(marketTypejComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(customerjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selretjButton))
                .addGap(38, 38, 38)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(newCusjButton)
                .addContainerGap(420, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void marketTypejComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_marketTypejComboBoxItemStateChanged
        customerjComboBox.setEnabled(true);
        String marketType = String.valueOf(marketTypejComboBox.getSelectedItem());
        try{
            Market market = business.getMarketDirectory().searchMarket(marketType);
        System.out.println(market.getMarketId());
        customerjComboBox.removeAllItems();
        for(Customer cus : market.getCustomerDirectory().getCustomerDirectory()){
            customerjComboBox.addItem(cus.getCustomerName());
        }
        }
        catch(Exception e){
            System.out.println("Something wrong");
        }
        
    }//GEN-LAST:event_marketTypejComboBoxItemStateChanged

    private void retCusjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retCusjButtonActionPerformed
        customerjComboBox.setEnabled(true);
        marketTypejComboBox.setEnabled(true);
        customerjComboBox.setEnabled(true);
        selretjButton.setEnabled(true);
    }//GEN-LAST:event_retCusjButtonActionPerformed

    private void newCusjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newCusjButtonActionPerformed
        /*Supplier supplier = business.getSupplierDirectory().searchSupplier(String.valueOf(marketTypejComboBox1.getSelectedItem()));
        CreateCustomerJPanel createCustomerJPanel = new CreateCustomerJPanel(userProcessContainerjPanel, supplier,"sales");
        userProcessContainerjPanel.add("CreateCustomerJPanel",createCustomerJPanel);
        CardLayout layout = (CardLayout)userProcessContainerjPanel.getLayout();
        layout.next(userProcessContainerjPanel);*/
    }//GEN-LAST:event_newCusjButtonActionPerformed

    private void selretjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selretjButtonActionPerformed
        Market market = business.getMarketDirectory().searchMarket(String.valueOf(marketTypejComboBox.getSelectedItem()));
        Customer customer = market.getCustomerDirectory().searchCustomer(String.valueOf(customerjComboBox.getSelectedItem()));
        OrderJPanel orderJPanel = new OrderJPanel(userProcessContainerjPanel,business,market,customer);
        userProcessContainerjPanel.add("OrderJPanel",orderJPanel);
        CardLayout layout = (CardLayout)userProcessContainerjPanel.getLayout();
        layout.next(userProcessContainerjPanel);
    }//GEN-LAST:event_selretjButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> customerjComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JComboBox<String> marketTypejComboBox;
    private javax.swing.JButton newCusjButton;
    private javax.swing.JButton retCusjButton;
    private javax.swing.JButton selretjButton;
    // End of variables declaration//GEN-END:variables

    
}
