/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.sales;

import Business.Business;
import Business.sales.OrderItems;
import Business.sales.PurchaseOrder;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

import org.jfree.chart.ChartPanel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.JFreeChart;
import org.jfree.ui.ApplicationFrame;
import org.jfree.ui.RefineryUtilities;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author sreer
 */


public class viewAllSalesJPanel extends javax.swing.JPanel {

    /**
     * Creates new form viewAllSalesJPanel
     */
    JPanel cardSeqjPanel;
    Business business;
    public viewAllSalesJPanel(JPanel cardSeqjPanel,  Business business) {
        initComponents();
        
        this.cardSeqjPanel = cardSeqjPanel;
        this.business = business;
        populateTable();
        
    }
    void populateTable(){
        int rowCount = purchaseOrderjTable.getRowCount();

        DefaultTableModel dtm = (DefaultTableModel) purchaseOrderjTable.getModel();

        for (int i = rowCount - 1; i >= 0; i--) {
            dtm.removeRow(i);
        }
        double totalSales = 0;
        double myCommission = 0;
        System.out.println(business.getPurchaseOrderCat().getPurchaseOrderCat().get(0).getTotalPrice());
        int sno = 1;
        try{
            for (PurchaseOrder m : business.getPurchaseOrderCat().getPurchaseOrderCat()) // 1st time getProductCatalog() is called in supplier and 2nd time the same method is called in product Catalog class. So we have 2 getProductCatalog()
            {
                if(m.getUser()==business.getLoggedUser()){
                    Object row[] = new Object[7];
                    row[0] = sno++;
                    row[1] = m;
                    row[2] = m.getCustomer().getCustomerName();                   // we hv created toString() so that, inspite of giving address of object we will get product name
                    row[3] = m.getMarket().getMarketType();
                    row[4] = m.getTotalPrice();
                    row[5] = String.valueOf(m.getDate());
                    System.out.println(m.getUser().getUserName());
                    row[6] = m.getUser().getUserName();
                    dtm.addRow(row);
                    totalSales +=m.getTotalPrice();
                    for(OrderItems ol : m.getOrderItemsCat().getOrderItemsCat()){
                        myCommission += ol.getCommissionEarned();
                    }
                }
                myCommissionjTextField.setText(String.valueOf(myCommission));
                totaljTextField.setText(String.valueOf(totalSales));
            }
        }
        catch(Exception e){
            
        }
    }
    

   private DefaultCategoryDataset createDataset( ) {
      DefaultCategoryDataset dataset = new DefaultCategoryDataset( );
      dataset.addValue( 15 , "schools" , "1970" );
      dataset.addValue( 30 , "schools" , "1980" );
      dataset.addValue( 60 , "schools" ,  "1990" );
      dataset.addValue( 120 , "schools" , "2000" );
      dataset.addValue( 240 , "schools" , "2010" );
      dataset.addValue( 300 , "schools" , "2014" );
      return dataset;
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        purchaseOrderjTable = new javax.swing.JTable();
        viewOrderItemsjButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        totaljTextField = new javax.swing.JTextField();
        myCommissionjTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("All Sales View");

        purchaseOrderjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Sno", "Purchase Id", "Customer", "Market", "Total Price", "Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(purchaseOrderjTable);

        viewOrderItemsjButton.setText("View Ordered Items");
        viewOrderItemsjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewOrderItemsjButtonActionPerformed(evt);
            }
        });

        jLabel2.setText("Total Sales");

        totaljTextField.setEditable(false);

        myCommissionjTextField.setEditable(false);

        jLabel3.setText("Commission");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(myCommissionjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(totaljTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(viewOrderItemsjButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(viewOrderItemsjButton)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(totaljTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(myCommissionjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(210, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void viewOrderItemsjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewOrderItemsjButtonActionPerformed
        int selectedRow = purchaseOrderjTable.getSelectedRow();
        System.out.println(selectedRow);
        if(selectedRow>=0)
        {
            
            PurchaseOrder vs = (PurchaseOrder)purchaseOrderjTable.getValueAt(selectedRow, 1);
            OrderItemsViewJPanel viewuser = new OrderItemsViewJPanel(cardSeqjPanel,business,vs);
            cardSeqjPanel.add("OrderItemsViewJPanel",viewuser);
            CardLayout layout = (CardLayout) cardSeqjPanel.getLayout();
            layout.next(cardSeqjPanel);
        }
        else{
            JOptionPane.showMessageDialog(null, "Please select a row");
        }
    }//GEN-LAST:event_viewOrderItemsjButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField myCommissionjTextField;
    private javax.swing.JTable purchaseOrderjTable;
    private javax.swing.JTextField totaljTextField;
    private javax.swing.JButton viewOrderItemsjButton;
    // End of variables declaration//GEN-END:variables
}
