/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.SalesPerson;

import Business.*;
import Business.Person.SalesPerson;
import java.awt.CardLayout;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Vaibhavi
 */
public class ManageSalesPersonJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageSalesPerson
     */
    private JPanel userProcessContainer;
    private Business business;
    
    public ManageSalesPersonJPanel(JPanel userProcessContainer, Business business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.business = business;
        populateTable();
    }

    public void populateTable()
    {
        DefaultTableModel defaultTableModel = (DefaultTableModel)salesPersonJTable.getModel();
        defaultTableModel.setRowCount(0);
        
        for(SalesPerson salesPerson : business.getSalesPersonDirectory().getSalesPersonDirectory())
        {
            Object row[] = new Object[3];
            row[0] = salesPerson;
            row[1] = salesPerson.getPerson().getFullName();
            row[2] = salesPerson.getTotalNumberOfSales();
            defaultTableModel.addRow(row);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        salesPersonIdTextField = new javax.swing.JTextField();
        searchSalesPersonBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        salesPersonJTable = new javax.swing.JTable();
        addSalesPersonBtn = new javax.swing.JButton();
        displaySalesPersonBtn = new javax.swing.JButton();
        deleteSalesPersonBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setBackground(new java.awt.Color(0, 102, 102));
        jLabel1.setFont(new java.awt.Font("Georgia", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Manage SalesPerson ");
        jLabel1.setOpaque(true);

        jLabel2.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel2.setText("SalesPerson ID :");

        salesPersonIdTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                salesPersonIdTextFieldKeyTyped(evt);
            }
        });

        searchSalesPersonBtn.setBackground(new java.awt.Color(0, 102, 102));
        searchSalesPersonBtn.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        searchSalesPersonBtn.setForeground(new java.awt.Color(255, 255, 255));
        searchSalesPersonBtn.setText("Search SalesPerson");
        searchSalesPersonBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.darkGray, null, null));
        searchSalesPersonBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchSalesPersonBtnActionPerformed(evt);
            }
        });

        salesPersonJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "SalesPerson ID", "SalesPerson Name", "Total Number of Sales"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(salesPersonJTable);

        addSalesPersonBtn.setBackground(new java.awt.Color(0, 102, 102));
        addSalesPersonBtn.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        addSalesPersonBtn.setForeground(new java.awt.Color(255, 255, 255));
        addSalesPersonBtn.setText("Add SalesPerson >>");
        addSalesPersonBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.darkGray, null, null));
        addSalesPersonBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSalesPersonBtnActionPerformed(evt);
            }
        });

        displaySalesPersonBtn.setBackground(new java.awt.Color(0, 102, 102));
        displaySalesPersonBtn.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        displaySalesPersonBtn.setForeground(new java.awt.Color(255, 255, 255));
        displaySalesPersonBtn.setText("Update/Display SalesPerson >>");
        displaySalesPersonBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.darkGray, null, null));
        displaySalesPersonBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displaySalesPersonBtnActionPerformed(evt);
            }
        });

        deleteSalesPersonBtn.setBackground(new java.awt.Color(0, 102, 102));
        deleteSalesPersonBtn.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        deleteSalesPersonBtn.setForeground(new java.awt.Color(255, 255, 255));
        deleteSalesPersonBtn.setText("Delete SalesPerson >>");
        deleteSalesPersonBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.darkGray, null, null));
        deleteSalesPersonBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteSalesPersonBtnActionPerformed(evt);
            }
        });

        backBtn.setBackground(new java.awt.Color(102, 0, 0));
        backBtn.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        backBtn.setText("<< Back");
        backBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.darkGray, null, null));
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(displaySalesPersonBtn, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(301, 301, 301)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(addSalesPersonBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(deleteSalesPersonBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(28, 28, 28)
                        .addComponent(salesPersonIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(searchSalesPersonBtn)
                        .addGap(56, 56, 56))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(salesPersonIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(searchSalesPersonBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(addSalesPersonBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(deleteSalesPersonBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(displaySalesPersonBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void salesPersonIdTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_salesPersonIdTextFieldKeyTyped

        char ch = evt.getKeyChar();
        if(!(Character.isDigit(ch)) || (ch == KeyEvent.VK_BACK_SPACE) || (ch == KeyEvent.VK_DELETE))
        {
            evt.consume();
            if(Character.isAlphabetic(ch) || Character.isSpaceChar(ch))
            JOptionPane.showMessageDialog(null,"Enter alphabetical values only.");
        }
    }//GEN-LAST:event_salesPersonIdTextFieldKeyTyped

    private void searchSalesPersonBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchSalesPersonBtnActionPerformed

        if(!salesPersonIdTextField.getText().isEmpty())
        {
            SalesPerson salesPerson = business.getSalesPersonDirectory().searchSalesPerson(Integer.parseInt(salesPersonIdTextField.getText()));

            if(salesPerson != null)
            {
                DisplaySalesPersonJPanel displaySalesPersonJPanel = new DisplaySalesPersonJPanel(userProcessContainer, salesPerson);
                userProcessContainer.add("DisplaySalesPersonJPanel",displaySalesPersonJPanel);
                CardLayout layout = (CardLayout)userProcessContainer.getLayout();
                layout.next(userProcessContainer);
            }
            else
            {
                JOptionPane.showMessageDialog(null, "The SalesPerson doesn't exist.","Information",JOptionPane.INFORMATION_MESSAGE);
            }
            salesPersonIdTextField.setText("");
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Please enter the CustomerId.","Warning",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_searchSalesPersonBtnActionPerformed

    private void addSalesPersonBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSalesPersonBtnActionPerformed

        CreateSalesPersonJPanel createSalesPersonJPanel = new CreateSalesPersonJPanel(userProcessContainer, business);
        userProcessContainer.add("CreateSalesPersonJPanel",createSalesPersonJPanel);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_addSalesPersonBtnActionPerformed

    private void displaySalesPersonBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displaySalesPersonBtnActionPerformed

        int selectedRow = salesPersonJTable.getSelectedRow();

        if(selectedRow >= 0)
        {
            SalesPerson salesPerson = (SalesPerson)salesPersonJTable.getValueAt(selectedRow, 0);
            DisplaySalesPersonJPanel displaySalesPersonJPanel = new DisplaySalesPersonJPanel(userProcessContainer, salesPerson);
            userProcessContainer.add("DisplaySalesPersonJPanel",displaySalesPersonJPanel);
            CardLayout layout = (CardLayout)userProcessContainer.getLayout();
            layout.next(userProcessContainer);
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Please select a row.", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_displaySalesPersonBtnActionPerformed

    private void deleteSalesPersonBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteSalesPersonBtnActionPerformed

        int selectedRow = salesPersonJTable.getSelectedRow();

        if(selectedRow >= 0)
        {
            SalesPerson salesPerson = (SalesPerson)salesPersonJTable.getValueAt(selectedRow, 0);
            business.getSalesPersonDirectory().deleteSalesPerson(salesPerson);
            populateTable();
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Please select a row.", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_deleteSalesPersonBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addSalesPersonBtn;
    private javax.swing.JButton backBtn;
    private javax.swing.JButton deleteSalesPersonBtn;
    private javax.swing.JButton displaySalesPersonBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField salesPersonIdTextField;
    private javax.swing.JTable salesPersonJTable;
    private javax.swing.JButton searchSalesPersonBtn;
    // End of variables declaration//GEN-END:variables
}
